version: '3'
 
services:
  pokedex:
    environment:
      - HOST_NAME="https://pokedex.automateyournetwork.ca"
    container_name: pokedex
    image: johncapobianco/pokedex:pokedex
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
    # volumes:
    #   - /etc/letsencrypt/archive/pokedex.automateyournetwork.ca/:/etc/letsencrypt/live/pokedex.automateyournetwork.ca/

  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=pokedex
      - POSTGRES_PASSWORD=pokedex
      - POSTGRES_DB=pokedex
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgadmin:
    driver: local

networks:
  all-plugins-nginx-proxy_app_network:
    name: all-plugins-nginx-proxy_app_network