version: '3'
 
services:
  pokedex:
    image: johncapobianco/pokedex:pokedex
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - db
    # volumes:
    #   - /etc/letsencrypt/archive/pokedex.automateyournetwork.ca/:/etc/letsencrypt/live/pokedex.automateyournetwork.ca/

  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=pokedex
      - POSTGRES_PASSWORD=pokedex
      - POSTGRES_DB=pokedex
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgadmin:
    driver: local